version: '2'
services:
    meetfit-app:
        image: meetfit
        external_links:
            - meetfit-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/meetfit?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    meetfit-mysql:
        extends:
            file: mysql.yml
            service: meetfit-mysql
